# Chart-level defaults (overridden by values-legion_caas.yaml via sharedValueFiles)
cluster:
  defaults:
    cloudProvider: aws
    cloudRegion: us-east-2
    instanceType: m5.xlarge
    workerReplicas: 3
    controlPlaneReplicas: 3
    controlPlaneMachineType: m5.xlarge
    clusterVersion: "img4.21.6-x86-64-appsub"
    rootVolumeSize: 120
    rootVolumeType: gp3

  credentials:
    namespace: cluster-provisioning
    secretStoreName: vault-backend
    awsCredsVaultKey: secret/data/hub/aws
    pullSecretVaultKey: pushsecrets/global-pull-secret

  providerConfigRef: default

global:
  crossplane:
    providerConfig:
      name: default
