clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - open-cluster-management
    - vault
    - golang-external-secrets
    - openshift-pipelines
    - cluster-provisioning
    - cert-manager-operator
    - legion-monitoring
#    - ack-system

  operatorgroupExcludes:
    - ack-system

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.16

    openshift-pipelines:
      name: openshift-pipelines-operator-rh
      channel: latest

    cert-manager:
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
      source: redhat-operators
      channel: stable-v1

#    ack-s3:
#      name: ack-s3-controller
#      namespace: ack-system
#      channel: alpha
#      source: community-operators

  argoProjects:
    - hub
    - infrastructure
#    - s3

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      argoProject: hub
      chart: acm
      chartVersion: 0.1.*

    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      argoProject: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*

    legion-credentials:
      name: legion-credentials
      namespace: cluster-provisioning
      argoProject: infrastructure
      path: charts/hub/legion-credentials
      overrides:
      - name: hypershiftOIDC.enabled
        value: true
      - name: hypershiftOIDC.region
        value: us-east-2
      - name: hypershiftOIDC.bucketName
        value: vp-hypershift-state

    hcp-cli:
      name: hcp-cli
      namespace: cluster-provisioning
      argoProject: infrastructure
      path: charts/hub/hcp-cli

    legion-pipelines:
      name: legion-pipelines
      namespace: cluster-provisioning
      argoProject: infrastructure
      path: charts/hub/legion-pipelines

    cert-manager-config:
      name: cert-manager-config
      namespace: cert-manager
      argoProject: infrastructure
      path: charts/hub/cert-manager-config

    legion-monitoring:
      name: legion-monitoring
      namespace: legion-monitoring
      argoProject: infrastructure
      path: charts/hub/legion-monitoring

    cluster-autoscaler:
      name: cluster-autoscaler
      namespace: openshift-machine-api
      argoProject: infrastructure
      path: charts/hub/cluster-autoscaler

#    ack-s3:
#      name: ack-s3
#      namespace: ack-system
#      argoProject: s3
#      path: charts/hub/ack-s3
#      overrides:
#      - name: oidc.region
#        value: us-east-2
#      - name: oidc.bucketName
#        value: vp-hypershift-state
#      - name: s3.createBucket
#        value: false

  imperative:
    namespace: imperative
    jobs:
    - name: hello-world
      playbook: rhvp.cluster_utils.hello_world
      timeout: 234

  managedClusterGroups:
    provisionedClusters:
      name: provisioned
      acmlabels:
      - name: clusterGroup
        value: provisioned
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
