# Chart-level defaults (overridden by global.* from values-legion_caas.yaml)
global:
  crossplane:
    providers:
      version: v2.4.0
      packages:
        - name: provider-family-aws
          package: xpkg.upbound.io/upbound/provider-family-aws
        - name: provider-aws-ec2
          package: xpkg.upbound.io/upbound/provider-aws-ec2
        - name: provider-aws-s3
          package: xpkg.upbound.io/upbound/provider-aws-s3
        - name: provider-aws-iam
          package: xpkg.upbound.io/upbound/provider-aws-iam

    kubernetesProvider:
      version: v1.2.1
      package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes

    providerConfig:
      name: default
      credentials:
        secretName: aws-provider-creds
        secretNamespace: crossplane-system
        secretKey: credentials
        fromVault: true

  hypershift:
    oidc:
      region: ""
      bucketName: ""
      createBucket: false
      publicReadAccess: true
      additionalTags: {}
