apiVersion: v1
kind: ConfigMap
metadata:
  name: perses-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: perses
data:
  config.yaml: |
    provisioning:
      folders:
        - /etc/perses/provisioning/datasources
        - /etc/perses/provisioning/dashboards
