{{- if .Values.global.crossplane.providerConfig.credentials.fromVault | default false }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-provider-creds
  namespace: {{ .Values.global.crossplane.providerConfig.credentials.secretNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.crossplane.providerConfig.credentials.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{ .Values.global.crossplane.providerConfig.credentials.secretKey }}: |
          [default]
          aws_access_key_id = {{`{{ .accessKeyID }}`}}
          aws_secret_access_key = {{`{{ .secretAccessKey }}`}}
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: secret/data/hub/aws
        property: aws_access_key_id
    - secretKey: secretAccessKey
      remoteRef:
        key: secret/data/hub/aws
        property: aws_secret_access_key
{{- end }}
