apiVersion: v2
name: legion-pipelines
description: OpenShift Pipelines for multi-tenant Hive and HyperShift cluster provisioning
keywords:
- pattern
- pipelines
- tekton
- hive
- hypershift
type: application
version: 0.1.0
appVersion: "0.1.0"
