{{- if .Values.clusterAutoscaler.enabled }}
apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  name: default
spec:
  balanceSimilarNodeGroups: {{ .Values.clusterAutoscaler.balanceSimilarNodeGroups }}
  skipNodesWithLocalStorage: {{ .Values.clusterAutoscaler.skipNodesWithLocalStorage }}
  logVerbosity: {{ .Values.clusterAutoscaler.logVerbosity }}
  resourceLimits:
    maxNodesTotal: {{ .Values.clusterAutoscaler.resourceLimits.maxNodesTotal }}
    cores:
      min: {{ .Values.clusterAutoscaler.resourceLimits.cores.min }}
      max: {{ .Values.clusterAutoscaler.resourceLimits.cores.max }}
    memory:
      min: {{ .Values.clusterAutoscaler.resourceLimits.memory.min }}
      max: {{ .Values.clusterAutoscaler.resourceLimits.memory.max }}
  scaleDown:
    enabled: {{ .Values.clusterAutoscaler.scaleDown.enabled }}
    delayAfterAdd: {{ .Values.clusterAutoscaler.scaleDown.delayAfterAdd }}
    delayAfterDelete: {{ .Values.clusterAutoscaler.scaleDown.delayAfterDelete }}
    delayAfterFailure: {{ .Values.clusterAutoscaler.scaleDown.delayAfterFailure }}
    unneededTime: {{ .Values.clusterAutoscaler.scaleDown.unneededTime }}
    utilizationThreshold: {{ .Values.clusterAutoscaler.scaleDown.utilizationThreshold | quote }}
{{- end }}
